apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicescommand
  template:
    metadata:
      labels:
        app: servicescommand
    spec:
      containers:
      - name: servicescommand
        image: wisdomnwachukwu/servicesascommands:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>

---
apiVersion: v1
kind: Service
metadata:
  name: commands-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: servicescommand
  ports:
  - name: servicescommand
    protocol: TCP
    port: 80
    targetPort: 80

