apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicesplatform
  template:
    metadata:
      labels:
        app: servicesplatform
    spec:
      containers:
      - name: servicesplatform
        image: wisdomnwachukwu/servicesplatforms:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
